#!/bin/sh
# Show dirty git repos

for d in */; do
  (
    cd $d
    status=`git status -s 2>/dev/null`
    if [ $? -ne 0 -o -n "$status" ]; then
      echo "== $d"
      git status -s
    fi
  )
done
